project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4200

format:
  html:
    smooth-scroll: true
    theme:
      light: litera
      dark: Cyborg
resource-path:
  - ./assets

toc: true
number-sections: true
number-depth: 3

metadata-files:
  - _website.yml

execute:
  cache: true
